#!/usr/bin/env bash

[[ "$1" ]] || {
  echo "usage: $0 LOG-OUT-DIR" >&2
  exit 1
}

rm -rf "logs/$1"

for dir in cockroach-data/*
do
  outdir="logs/$1/$(basename "$dir")"
  mkdir -p "$outdir"
  cp "$dir"/logs/*.log "$outdir"
done
